apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-my-app
  template:
    metadata:
      labels:
        app: deployment-my-app
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'while true; do echo $(date -u) "My k8s homework @ Netology sample log">> /busy/log.txt; sleep 5; done;']
        volumeMounts:
        - name: busybox-volume
          mountPath: "/busy"
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: busybox-volume
          mountPath: "/busy"
      volumes:
      - name: busybox-volume
        emptyDir: {}
